// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

enum Role { NONE, SESSION, OWNER }

enum ActionType { SWAP }

enum DecisionStatus { NONE, BLOCKED, APPROVED, EXECUTED, EXPIRED, CANCELLED }

enum ReasonCode {
    OK,
    ASSET_NOT_ALLOWED,
    ADAPTER_NOT_ALLOWED,
    SINGLE_ASSET_EXPOSURE_EXCEEDED,
    TRADE_SIZE_EXCEEDED,
    DAILY_TURNOVER_EXCEEDED,
    COOLDOWN_ACTIVE,
    PRICE_STALE,
    SESSION_EXPIRED,
    RECIPIENT_NOT_ALLOWED,
    SLIPPAGE
}
